"""Add coluna descricao

Revision ID: 760c7c41c4b8
Revises: 784b3d6c2005
Create Date: 2026-04-07 16:23:03.927800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760c7c41c4b8'
down_revision: Union[str, Sequence[str], None] = '784b3d6c2005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricap', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'descricap')
    # ### end Alembic commands ###
