"""Criando as tabelas

Revision ID: 784b3d6c2005
Revises: 
Create Date: 2026-04-07 15:58:24.826206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784b3d6c2005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_curso', sa.String(length=100), nullable=False),
    sa.Column('carga_hr', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_table('alunos',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_aluno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id_curso'], ),
    sa.PrimaryKeyConstraint('id_aluno'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
