"""Atualizando a coluna descricao

Revision ID: e6ec64b13981
Revises: 760c7c41c4b8
Create Date: 2026-04-07 16:24:06.255793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ec64b13981'
down_revision: Union[str, Sequence[str], None] = '760c7c41c4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricao', sa.String(length=150), nullable=True))
    op.drop_column('cursos', 'descricap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricap', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('cursos', 'descricao')
    # ### end Alembic commands ###
